Repository vinothdevelop/HTMLReport4Jest, pull requests merged in 2020-08, with the labels that each got.

#42 chore(lint) : fixed linting issues
  .eslintrc
  .prettierrc
  jest.config.js
  package.json
  src/App.js
  src/Components/Grid/GridTabView.js
  src/Components/Grid/TabContent.js
  src/Components/Grid/TabHeading.js
  src/Components/Header/Header.js
  src/Components/Main/Main.js
  src/Components/Modal/Modal.js
  src/Components/Sidebar/Sidebar.js
  src/Components/Summary/Summary.js
  src/Components/Summary/SummaryElement.js
  src/Components/TreeView/LeafNode.js
  src/Components/TreeView/ParentNode.js
  src/Components/TreeView/Treenode.js
  src/Components/TreeView/Treeview.js
  src/Utilities/DateUtilities.js
  src/index.js
  webpack.development.config.js
Labels: CI

#43 chore(deps) : dependabot update setup added
  .github/dependabot.yml
Labels: CI

#46 feat(UI) : improve popup design
  .eslintrc.json
  .github/workflows/node.js.yml
  .github/workflows/release.yml
  index.js
  jest.config.js
  package.json
  src/App.js
  src/Components/Grid/TabContent.test.js
  src/Components/Grid/TabHeading.js
  src/Components/Grid/TabHeading.test.js
  src/Components/Header/Header.js
  src/Components/Header/Header.test.js
  src/Components/Modal/ErrorMessage.css
  src/Components/Modal/ErrorMessage.js
  src/Components/Modal/ErrorMessage.test.js
  src/Components/Modal/Information.css
  src/Components/Modal/Information.js
  src/Components/Modal/Information.test.js
  src/Components/Modal/Modal.css
  src/Components/Modal/Modal.js
  src/Components/Modal/Modal.test.js
  src/Components/Modal/__snapshots__/ErrorMessage.test.js.snap
  src/Components/TreeView/ParentNode.test.js
  src/Utilities/DateUtilities.test.js
  src/index.js
  webpack.build.config.js
  webpack.common.js
Labels: UI/UX, enhancement

#47 feat(Reporter) : Display project level custom information
  README.md
  artifacts/Report.png
  jest.config.js
  package.json
  src/App.js
  src/Components/Main/Main.js
  src/Components/Main/Main.test.js
  src/Components/Modal/ErrorMessage.test.js
  src/Components/Modal/Information.css
  src/Components/Modal/Information.js
  src/Components/Modal/Information.test.js
  src/Utilities/DateUtilities.js
  src/Utilities/DateUtilities.test.js
Labels: Reporter, UI/UX, enhancement

#48 fix(CI) : fixed release pipeline
  .github/workflows/release.yml
Labels: CI, bug

#49 Add additional reporter option
  README.md
Labels: enhancement

#50 feat(UI): Add default project information
  README.md
  src/App.js
  src/App.test.js
  src/Components/Information/Information.css
  src/Components/Information/Information.js
  src/Components/Information/Information.test.js
  src/Components/Main/Main.js
  src/Components/Modal/Information.test.js
  src/Components/Modal/Modal.js
  src/Utilities/DateUtilities.js
  src/Utilities/DateUtilities.test.js
Labels: Reporter, enhancement

#51 Fix(docs): fix boolean spelling
  README.md
Labels: bug, documentation

#53 chore(lint): add lint for react hooks
  .eslintrc.json
  package.json
Labels: CI

#54 chore(docs): update homepage url
  package.json
Labels: documentation

#55 BREAKING CHANGE: redesign menu and sidebar with different UI style
  public/index.html
  src/App.js
  src/App.test.js
  src/Components/Grid/TabContent.test.js
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/Header/Header.test.js
  src/Components/Header/__snapshots__/Header.test.js.snap
  src/Components/Modal/Modal.css
  src/Components/Sidebar/Sidebar.css
  src/Components/Sidebar/Sidebar.js
  src/Components/Sidebar/Sidebar.test.js
  src/Components/TreeView/ParentNode.test.js
  src/Components/TreeView/Treenode.css
  src/Components/TreeView/Treenode.js
  src/__snapshots__/App.test.js.snap
  webpack.development.config.js
Labels: UI/UX, enhancement

#64 chore(badge): Add install size badge
  README.md
Labels: documentation
